### ISSUE TITLE
Broken link for Event Loop and Microtasks 

### ISSUE THREAD

**Issue by stankotrcek** [lrlna/smol-zines#10]
Hi, link for Event Loop and Microtasks is broken; shold be:  [https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/](https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/)

**Comment by lrlna** [comment]
thanks! fixed in https://github.com/lrlna/sketchin/commit/de0e0d109794f4a14cbd3d5a42e9931350b51969
